#!/bin/bash
# A.R.B. Configuration File
# THIS IS ONLY A TEMPLATE

# ENVIRONMENT
config="$HOME/config/arb"

# System
system_repo="$HOME/.archive/system"         # system repository
system_exclude="audisp brlapi.key ca-certificates crypttab default/useradd gshadow* iptables libaudit.conf mtab NetworkManager/system-connections pacman.d/gnupg polkit-1 .pwd.lock shadow* sudoers sudoers.d ufw"              # system exclude list

# Home
home_repo="$HOME/.archive/home"             # borg repository
home_exclude="$config/home.ignore"          # borg exclude file
home_pass="home"                            # gocryptfs password
home_rsync="/mnt/backup/name"               # rsync destination dir
home_rclone=(nextcloud onedrive amazons3)   # rclone destination streams

# TASKS
# System Archive
archiveSys -o "$system_repo" -e "$system_exclude"

# Borg Archive
archiveBorg -n "home" -i "$HOME" -o "$home_repo" -e "$home_exclude"

# Repo Sync to Disk
syncDisk -n "home" -i "$home_repo" -o "$home_rsync"

# Repo Sync to Cloud
mountCrypt -n "home" -i "$home_repo" -p "$home_pass" || exit 1
syncCloud -n "home" -s "$home_rclone"
umountCrypt -n "home"
