#!/bin/bash
# A.R.B. Configuration File
# ENVIRONMENT
config="$HOME/config/arb"

# System
system_repo="$HOME/.archive/system"         # system repository
system_exclude="audisp brlapi.key ca-certificates crypttab default/useradd gshadow* iptables libaudit.conf mtab NetworkManager/system-connections pacman.d/gnupg polkit-1 .pwd.lock shadow* sudoers sudoers.d ufw"              # system exclude list

# Home
home_repo="$HOME/.archive/home"                     # borg repository
home_exclude="$config/home.ignore"           # borg exclude file
home_crypt="/tmp/$USER/name-crypt"          # gocryptfs encrypted dir
home_pass="home"                            # gocryptfs password
home_rsync="/mnt/backup/name"               # rsync destination dir
home_rclone=(nextcloud onedrive amazons3)   # rclone destination streams

# TASKS
# System Archive
archiveSys "$system_repo" "$system_exclude" & child=$! && wait $child

# Borg Archive
archiveBorg "$home_repo" "$home_exclude" "$home_src" & child=$! && wait $child

# Repo Sync to Disk
syncDisk "$home_repo" "$home_rsync" & child=$! && wait $child

# Repo Sync to Cloud
mount="$home_crypt" && mountCrypt "$home_repo" "$mount" "$home_pass" || exit 1
for stream in "${home_rclone[@]}"; do syncCloud name "$home_repo" "$stream" & child=$! && wait $child; done
