#!/bin/bash
# Invoke this to initialize a backup environment from the config file.
# WIP. This is a work in progress.

mountCrypt() { # args: # name $src $pass $exclude(opt)
    gocryptfs -extpass pass -extpass $name_pass -init -reverse "$repo"
}

syncCloud() { # syncCloud $name $streams $src(opt)
    rclone config
}

archiveSys() { # args: $repo $exclude
    git -C "$repo" init
}

archiveBorg() { # args: $borg_repo $borg_exclude $src $borg_pass(opt) $borg_key(opt)
    borg init -e none "$repo"
}

# Source variables and commands from config file
config="$HOME/.config/arb/config"
if [ -f "$config" ]; then # exit with config not found
    source "$config"
else
    printf "<3>ERROR: %s\n" "config file not found!"
    exit 1
fi

