.TH "ARB" 1

.SH "Automatic Robust Backup"

.PP
Automatic Robust Backup or A\.R\.B\. is an archiving and synchronization tool with automation, encryption, redundancy and performance as it goals\. It is fast to deploy, have sensible defaults and come with templates for common use cases\.

.SS "About"

.SB "Goals"
.RS
.Bl
.IP \(bu 4
\fBAutomation\fP: after configuration it should not require intervention\.
.El
.Bl
.IP \(bu 4
\fBEncryption\fP: man\-in\-the\-middle or server should not be able to read the data content\.
.El
.Bl
.IP \(bu 4
\fBRedundancy\fP: data should not be lost even if a catastrophic failure happens\.
.El
.Bl
.IP \(bu 4
\fBPerformance\fP: tasks should be done in a timely manner and conserve limited resources like size when possible\.
.El
.RE

.SB "Dependencies"
.RS
.Bl
.IP \(bu 4
Borg[28], the most popular chunk\-based deduplication backup manager for home users\.
.El
.sp
[28] https://github\.com/borgbackup/borg 
.nf
.fi
.Bl
.IP \(bu 4
Gocryptfs[29], the spiritual successor to Ecryptfs that is mature, audited actively developed\.
.El
.sp
[29] https://github\.com/rfjakob/gocryptfs 
.nf
.fi
.Bl
.IP \(bu 4
Rclone[30] is a mature command line cloud storage manager that supports most if not all common providers\.
.El
.sp
[30] https://github\.com/rclone 
.nf
.fi
.Bl
.IP \(bu 4
Rsync[31] is the best way to sync a directory to another local or network directory\.
.El
.sp
[31] https://github\.com/WayneD/rsync 
.nf
.fi
.Bl
.IP \(bu 4
Git[32] is the most popular version control system\.
.El
.sp
[32] https://github\.com/git/git 
.nf
.fi
.Bl
.IP \(bu 4
Pass[33], the standard UNIX password manager, or gopass[34], its actively developed Go fork\.
.El
.sp
[33] https://www\.passwordstore\.org/ 
.nf
.fi
[34] https://github\.com/gopasspw/gopass 
.nf
.fi
.RE

.SB "Features"
.RS
.Bl
.IP \(bu 4
Save space via Borg's fast and effective deduplication and compression\.
.El
.Bl
.IP \(bu 4
Do daily, or even more granular, archives and mount them wherever you want to check the repository at that time\.
.El
.Bl
.IP \(bu 4
Set complex retention policies to control repository size while preserving time span coverage\. 
.El
.Bl
.IP \(bu 4
Ensure privacy and integrity of data stored on cloud through Gocryptfs online encryption\.
.El
.Bl
.IP \(bu 4
Sync your data to over 40 cloud storage services, including all major providers with free tiers \fI(Google Drive, Dropbox, Onedrive, Mega, etc)\fP\.
.El
.Bl
.IP \(bu 4
Store secrets encrypted with GPG key and Git versioned\.
.El
.Bl
.IP \(bu 4
Archive system configuration files and package list\.
.El
.Bl
.IP \(bu 4
Archive your personal files and whatever files you wish\.
.El
.RE

.SS "Install"

.SB "Globally"
.PP
If you're in an Arch based distro, install with an AUR helper like paru[35] or build manually the PKGBUILD[36]\.
.sp
[35] https://github\.com/Morganamilo/paru 
.nf
.fi
[36] https://aur\.archlinux\.org/packages/arbie\-git/ 
.nf
.fi

.PP
If you're in another distro you can install via make\.
.RS
.PP
.nf
$ make
$ make install
.fi
.RE

.SB "Locally"
.PP
Installing locally may be advantageous in systems for which ARB isn't packaged or for users of systemd\-homed[37] that share their home between systems\. 
.sp
[37] https://wiki\.archlinux\.org/index\.php/Systemd\-homed 
.nf
.fi

.RS
.PP
.nf
$ \./setup install
.fi
.RE

.SS "Configure"

.SB "Pipelines"
.PP
Edit `\f[CR]\.config/arbie/config\fP` to set up pipelines\. Instructions and examples included in the file\.

.SB "Init"
.PP
Some of the tools require manual initialization or configuration\. In the future there will be a tool to partially automate those\. 

.SB "Pass"
.PP
Init a password repository
.RS
.PP
.nf
$ gopass setup
.fi
.RE
.PP
\fINote: A GPG key is needed\.\fP
.PP
Generate a long secure password
.RS
.PP
.nf
$ pass generate $secret_name
.fi
.RE
.PP
Insert a password manually
.RS
.PP
.nf
$ pass insert $secret_name
.fi
.RE
.PP
\fINote: They will be needed later for encryption\.\fP 

.SB "System"
.PP
Init Git in System repository
.RS
.PP
.nf
$ git \-C $repo_path init
.fi
.RE

.SB "Borg"
.PP
Init Borg repository
.RS
.PP
.nf
$borg init \-e none $repo_path
.fi
.RE
.PP
\fINote: Encryption is done by gocryptfs\.\fP

.SB "Gocryptfs"
.PP
Init reverse mode encryption in a dir
.RS
.PP
.nf
$ gocryptfs \-extpass pass \-extpass $secret_name \-init \-reverse $repo_path
.fi
.RE
.PP
\fINote: Reverse mode encryption mount plain dir and files as encrypted files with encrypted dir names which is ideal for storing on the cloud\.\fP

.SB "Rclone"
.PP
Configure streams
.RS
.PP
.nf
$ rclone config
.fi
.RE

.SB "Service"
.PP
Enable the systemd timer as user
.RS
.PP
.nf
$ systemctl \-\-user enable arbie\.timer
.fi
.RE
.PP
By default it will try to run daily at midnight and run immediately after login in case of a miss\. But you edit the service to make it run whenever you want by using a cron alike syntax\.
.RS
.PP
.nf
$ systemctl \-\-user edit arbie\.timer
.fi
.RE
.PP
More information about that on Arch Wiki: Systemd/Timers[38]
.sp
[38] https://wiki\.archlinux\.org/index\.php/Systemd/Timers 
.nf
.fi


.SS "Maintenance"

.SB "Borg"
.PP
Before anything, export the repository path\. 
.RS
.PP
.nf
$ export BORG_REPO="$repo_path"
.fi
.RE
.PP
Show repository info
.RS
.PP
.nf
$ borg info
.fi
.RE
.PP
List archives
.RS
.PP
.nf
$ borg list
.fi
.RE
.PP
Mount an archive with FUSE
.RS
.PP
.nf
$ borg mount ::archiveName mountPoint
.fi
.RE

.SS "Extra"

.SB "Vault"
.PP
Vault Guardian unlock/lock an encrypted at rest directory (a\.k\.a\. Vault)\.
.RS
.PP
.nf
$ vaultguard unlock
.fi
.RE
.PP
To use it create the file `\f[CR]$HOME/\.config/arbie/vault\.conf\fP` and configure following the template at `\f[CR]/usr/share/arbie\fP`\.
.PP
And initialize a gocryptfs files system in the chosen path
.RS
.PP
.nf
$ gocryptfs \-extpass pass \-extpass $secret_name \-init $vault_path
.fi
.RE

.SS "Caveats"

.SB "Security"
.PP
Security is a big concern\. \fBRclone\fP and \fBBorg\fP have their own encryption features but following the principle of do one thing and do it well \fBGocrypts\fP is exclusively an audited encryption file system\.
.PP
\fINote: The repeated and thus predictable header pattern of Borg files may be a vector for a sophisticated attack\.\fP

.SB "For each their own"
.PP
There is no ideal backup method\. But for most users their data can be classified in an ABC fashion: few files that they really can't lose; data with average volume and importance; voluminous but not important data\. And each of these categories will have their own ideal methods\.

.SB "Cloud synchronization"
.PP
Cloud providers are a cheap way to have an off\-site copy replicated in data centers globally\. Some people may have a limited Internet connection and may find useful to instead sync a secondary archive with higher compression and heavy use of exclusion patterns while syncing a full archive on premise\.

.SB "Granularity"
.PP
File\-based is simpler but the controlled granularity of chunk\-based is ideal\. To sync a few large size files would be a PITA because any modification would require a re\-upload of the whole file\. On the other side to sync a great number of small files directly would congest the API requests quota\. \fBBorg\fP allows tuning the chunk size and is performant\.

.SB "System backup"
.PP
Reinstalling is faster and saner than doing whole disk backups\. It's more practical to backup the system configurations and a list of installed packages\. After a fresh minimal install the user can run a script to recover the system settings\. The advantages are: no need to restart; instantly done; no voluminous disk images or tar archives; high\-granularity history of system changes\.

.SB "Task automation"
.PP
Desktops generally don't stay on 24/7 so there's a need for a tool that will reschedule missed tasks\. \fBAnacron\fP does that but unfortunately it would require the scripts to run as root\. While \fBSystemd\fP allows the scripts to run in the user environment and provides it's own logging feature through \fBJournalctl\fP\. Also many distros are coming only with \fBSystemd\fP installed\.
